CREATE TABLE IF NOT EXISTS b2b.hotel_booking
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    booking_id character varying COLLATE pg_catalog."default" NOT NULL,
    booking_date date NOT NULL,
    checkin date NOT NULL,
    checkout date NOT NULL,
    payment_status character varying COLLATE pg_catalog."default" NOT NULL,
    status character varying COLLATE pg_catalog."default" NOT NULL,
    agency_id integer NOT NULL,
    contact_no character varying COLLATE pg_catalog."default",
    whatsapp_no character varying COLLATE pg_catalog."default",
    refundable boolean,
    note text COLLATE pg_catalog."default",
    holder json,
    grn_price json,
    sell_price json,
    booking_reference character varying COLLATE pg_catalog."default",
    booking_comment text COLLATE pg_catalog."default",
    search_id character varying COLLATE pg_catalog."default",
    booked_by integer,
    hotel_data json,
    cancellation_data json,
    currency character varying COLLATE pg_catalog."default",
    finalized boolean,
    modified_booking_id character varying COLLATE pg_catalog."default",
    dscv_payment_status character varying COLLATE pg_catalog."default",
    remarks text COLLATE pg_catalog."default",
    booking_type character varying COLLATE pg_catalog."default",
    hotel_extra_charges json,
    supports_cancellation boolean,
    supports_amendment boolean,
    h_confirmation_no character varying COLLATE pg_catalog."default",
    currency_conversion_rate numeric,
    agencies_sell_price json,
    agencies_cancellation_data json,
    is_auto_cancelled boolean,
    is_req_sent_for_cancellation boolean,
    book_from b2b.book_from_type DEFAULT 'Portal'::b2b.book_from_type,
    CONSTRAINT hotel_booking_pkey PRIMARY KEY (id)
);
